### ISSUE TITLE
Dear Fonyo -  please help me...

### ISSUE THREAD

**Issue by imrecsoka** [aaronsace/MultiPoolMiner#173]
hi i see you have a fork but i dont understand what i need to do ?
please help me or set it up for me (teamview)
thanks

**Comment by fonyo** [comment]
Please post this at my fork's issues section as your request is quite irrelevant and inappropriate here.

**Comment by imrecsoka** [comment]
I cant find your issues so i can post, no idea why 
i went to github/fonyo and then click on your dualmining project but there is no issues link

**Comment by fonyo** [comment]
Issues section should be there now, don't know why it got disabled. Head over there with your request. Bear in mind, my fork is pre-alpha, not sure what exactly you expect from it. I created it mostly because I wanted to include the miners I mentioned in the extreme benchmarking topic but since it turned into a testbed for the linux version which is on halt due to the lack of test equipment due to stock shortages.
