### ISSUE TITLE
Have a gtx 1070 and gtx 1080  how do i tell the miner to only utilize the gtx 1080? Thanks!

### ISSUE THREAD

**Issue by SS2006** [aaronsace/MultiPoolMiner#174]
Is it possible? Appreciate it

**Comment by aaronsace** [comment]
You would have to edit the commands in the files within the 'miners' folder. 

I assume you are wanting to mine on the secondary card whilst still using your machine.

**Comment by JohnS33** [comment]
Yes exactly. so i'd have to add that to all the miners in the miners folder?

**Comment by SS2006** [comment]
Yes exactly. so i'd have to add that to all the miners in the miners folder?

**Comment by fonyo** [comment]
If your 1080 is sitting under your 1070, it is highly likely 1070 will be GPU0 and your 1080 will be GPU1 (you can confirm this with eg. AIDA64). Based on this assumption, for eg. Claymore miner configs you can add "di 1" to only enable mining on GPU1. I would restrict mining to ethash and zcash algorithms to decrease the amount editing that needs to be done as these algorithms are most likely the most profitable anyway (especially since we are only talking about mining with a single card). I hope this helps.

**Comment by fonyo** [comment]
https://github.com/aaronsace/MultiPoolMiner/issues/155
