### ISSUE TITLE
Honest question about profitability

### ISSUE THREAD

**Issue by ghost** [aaronsace/MultiPoolMiner#175]
Has anyone experimented or crunched the numbers, is multi algo mining via this (or any program) via MPH, more profitable than straight mining

For example if I just download EWBF zcash, or claymore dual ether, and straight mine zcash or ether, 
would I make more zcash or ether instead if I use this program and set auto exchanged coin to zcash or ether on MPH etc?

Significant different?

THanks alot, I've always wondered this

**Comment by aaronsace** [comment]
Measuring final profits can be highly inaccurate. In the end, everything is just statistics based on factual figures; you will earn more or less than what is shown statistically but if one algorithm is statistically more profitable then it is more likely to be profitable even if it is not. 

Flipping a coin with only two possible outcomes will only be 50% heads some of the time.

**Comment by JohnS33** [comment]
interesting, so if eth is my end goal, auto exchange via this is prob better. Though I heard GTX 1070 is as good as AMD for eth
what about zec? nvidia seems to do better there

**Comment by aaronsace** [comment]
This is not used by MultiPoolMiner but gives you an excellent analysis of the figures from coin data and exchanges: https://whattomine.com

**Comment by Jaerin** [comment]
Multi-algo mining is likely going to give you a more consistent return over time and not risk throwing all your eggs in one basket.  Even looking at whattomine will only tell you what is most profitable based on the factors you put into it.  The difficult could double or halve, the price could double or halve, or any other possible outcomes that will affect your value today.  What multi-algo at least seems to try to do is maximize your profits in a given moment based on the current conditions.  The problem is how quickly does your mined coins get converted to some other currency and how stable is that currency?

**Comment by imrecsoka** [comment]
I wish i knew how the hell to use whattomine  as it seems to return weird results to me so i obviously dont know how to use it.
If somebody is reading this and wants to give me a rundown in pictures or teamview please let me know.

**Comment by Jaerin** [comment]
I'm guessing the weird results you are getting are from Groestl which for whatever reason is measuring the actual Groestl algorithm instead of usually people use Myriad-Groestl for those coins now which actually gives about 45% higher hashrate.  Basically all you need to do is let MultipoolMiner or any other miner, mine the algorithm on a pool for a while to see what Hashrate you get for each algorithm.  Then plug the values into the various entries for each algorithm.  There are many algorithms that aren't on the front page, such as Skein, but you can go to individual coin calculators for those.  Fill in the power usage and cost of power if you want and which exchanges to check.  Finally click the calculate button and it will give a list of coins and what the return should be based on the current difficulty.  If you gave some specifics about what you are seeing I might be able to assist.
