### ISSUE TITLE
"MultiPoolMinder is x% more profitable:" but it does not switch

### ISSUE THREAD

**Issue by StyleForceOne** [aaronsace/MultiPoolMiner#184]
Hello,
He sometimes writes to me that the multipoolminer is more profitable than the current but still does not switch. What do I have to change it?
I would like to use all the there, how does a real bat file out so it works?
Have a rig with geforce and amd, but will hopefully soon split on 2 with only amd and geforce.

Can I actually use the multipool miner in other pools than minepoolhub?

Please excuse my bad english (google translate).
Best regards

![multipoolminer3](https://user-images.githubusercontent.com/29683053/27513025-4a1d75ca-5957-11e7-8b49-088b57929f85.png)

![multipoolminer31](https://user-images.githubusercontent.com/29683053/27513045-b7a75dee-5958-11e7-9d5a-7c2928211a48.png)

**Comment by Jaerin** [comment]
The Multipoolminer is XX% more profitable means that the calculated earnings of multipoolminer switch to different algorithms would be that much more profitable than if it had just mined that one particular algorithm the whole time.  The number is still only an estimate of your earnings on the pool and may not directly reflect what you actually get paid.  On Miningpoolhub and other multiple algorithm pools they have fluctuating values of the coins and multipoolminer switches to the one that is calculates should be the most profitable at that time.  Because each pool has different delays in exchange and payout the amount you actually earn my be very different.

There is some code to allow Multipoolminer to work on zpool.ca as well, but it may not be fully working yet.  There is also a pull request to the code to enable Yiimp, but I believe aaronsace wants to get Miningpoolhub and zpool stable first before trying to add more.

**Comment by StyleForceOne** [comment]
Ok many thanks for the info, actually I'm watching that he sometimes changes. Why does not he change now to the more profitable if he is so much better? So I set something wrong?
I want him to always be the most profitable.
What should I write in the bat file and insert on the site? ;)
That's what everybody wants. or not? ;)

This is my bat file:
`setx GPU_FORCE_64BIT_PTR 1
setx GPU_MAX_HEAP_SIZE 100
setx GPU_USE_SYNC_OBJECTS 1
setx GPU_MAX_ALLOC_PERCENT 100
setx GPU_SINGLE_ALLOC_PERCENT 100

powershell -version 5.0 -noexit -executionpolicy bypass -windowstyle maximized -command "&.\multipoolminer.ps1 -username MYUSERNAME -workername multipoolminer -interval 60 -location europe -ssl -type amd,nvidia -algorithm cryptonight,ethash,equihash,groestl,lyra2z,neoscrypt,pascal,sia -poolname miningpoolhub -currency btc,eur"`

thank you =)

**Comment by aaronsace** [comment]
MultiPoolMiner miner is you. More detail is coming in the next release.
