### ISSUE TITLE
How is Profitability computed

### ISSUE THREAD

**Issue by edobez** [aaronsace/MultiPoolMiner#233]
Hello,
I am seeing big differences between the computed profitability and the one I can see in WhatToMine.
Where are the profitability data taken from and what is the update rate?
Are the values averaged on a long term trend?

**Comment by aaronsace** [comment]
They are live stats from the pool.

**Comment by aaronsace** [comment]
The overall profit at the bottom is the week average.

**Comment by maxbaluev** [comment]
Where is the algorithm in the code that considers this?

**Comment by aaronsace** [comment]
The network difficulty and exchange rate is factored in here: 
https://miningpoolhub.com/?page=home&normalize=none

**Comment by fonyo** [comment]
@aaronsace "The network difficulty and exchange rate is calculated at the pool"

Which is the live stats delayed by 15 minutes to upto a half an hour as per MPH on bitcointalk.

**Comment by Nebiforever** [comment]
This 15 minutes up to 30 minutes delay on update is killing the usability and profit of algo switching than? 

some times (most of the times) the mpm switches algo every 5 mins (interval set to 300) because there is more profitable coin to mine according to pool live stats. (which can be delayed 15 to 30 minutes)  so there is a big chance of us mining the wrong algo (much less profit than mpm think) most of the time? 

could this be the reason why i am getting 0.0038-0.0040 btc/day even mpm shows average of 0.0055-0.0060 btc / day. (after profit reset) 

am i getting it wrong or?

**Comment by aaronsace** [comment]
The pool webpage is updated on a timer. The stats API is updated every 3 minutes. 

Not related to that anyway. The stats are broken, something has gone wrong on the pool.

**Comment by Nebiforever** [comment]
So the thing mph mentioned was about web page? 

The api is 3 mins delayed in worst case scenario than?

**Comment by Nebiforever** [comment]
and aproximately how much difference is acceptable between average profit mpm says and the real profit gained in pool. (with interval set to 300)

**Comment by aaronsace** [comment]
I've indicated the margin of error; it starts at +/- 50% and reduces as you run it for a few days.

**Comment by Nebiforever** [comment]
even after a week i am getting 0.0038-0.0040 btc/day even mpm shows average of 0.0055-0.0060 btc / day

sounds odd.

**Comment by papampi** [comment]
There is a problem at miningpoolhub api not updating at 3 minutes and updating much longer, I just tweeted to @minigpoolhub and told him the issue. 
Tweet and ask him to fix it too.

**Comment by papampi** [comment]
I think for now its best to only mine ethereum+equihash+sia till its fixed
