### ISSUE TITLE
Feature request - Have next miner start before killing the previous miner

### ISSUE THREAD

**Issue by Jaerin** [aaronsace/MultiPoolMiner#245]
I was just trying to think of a way to eliminate some of the loss associated with the switching and start up time of the miners.  I wonder if it would be possible to fire up the next miner while the existing miner was still hashing and then kill the old one.  That way you at least continue mining something while the new miner fires up.  It may not seem like a lot, but over time that transition time can really eat into your profits a lot.

The problem I could see is when you have transition from ccminer to ccminer which is likely going to want to use the same port so that might need to be accounted for.

**Comment by aaronsace** [comment]
It used to do this but it causes problems with ports, memory allocation and GPUs locking up. Instead, I've reduced switching and will improve API support for miners.

**Comment by Jaerin** [comment]
Yeah I guess I could see that if you end up switching between two miners that take a ton of memory and have a limited mining rig.  Maybe a configurable option as to how much more profitable the next algorithm has to be before switching?  I've noticed sometimes it seems to flap a lot.   Or maybe an option to say that once a miner starts it has to run for X time before considering a change, but after that check every 1 minute.   Like the miner has to run at least 10 mins, but after that checks every minute for purposes of switching.

**Comment by scaras** [comment]
command to close, sleep 1 sec, check if closed, sleep 1 sec, start new miner. this looks to me the best option to switch between miners. and optional minimum mining time (2 → 5 rounds)?

**Comment by Jaerin** [comment]
There were only issues when multiple miners were open which is what the solution I was proposing to prevent the time between miner switches being unproductive by overlapping the miners.  I think the current mining closing process is working just fine at least on the ones that support the API.

**Comment by fonyo** [comment]
https://github.com/aaronsace/MultiPoolMiner/issues/112
As Aaron said, it is not a good idea to overlap miners. Some AMD cards/drivers are a bit more sensitive and the outcome is a BSOD.

**Comment by scaras** [comment]
with the delay you have less BTC loss then when 2 miners run on one card.
i run the miners 24/7 on my pc, (only turn them of when i (or my kids) want to play a game.
(i'm 36y old now with iq of 126 at my 15y)

i don't just install and run the bastard...
spending days on a simple oc for one card and multiple hours per algo for each miner to get the best results (speed/heat/power consumption) 

having dual screens, i have all info (MPM main window, miner windows and afterburner) on one screen while i'm working with the 2nd screen. double miners (or not switching) mostly happens when Zpool just has lost connection or when cpu is 100% in use (thats why i don't use core 1 with cpu mining)

it's always better to check if there is a miner running before opening the next.

**Comment by Jaerin** [comment]
No worries just a suggestion
