### ISSUE TITLE
Some notes on AMD and latest version of MPM

### ISSUE THREAD

**Issue by Imaminer** [aaronsace/MultiPoolMiner#310]
A: Gatelessgate does not work on Nicehash. Author of Gateless now works for NiceHash and is creator of Excavator.
B: Prospector is crashing and or never really starting. I am trying to find some log of an error but can't find one. This happens on all rigs. Please investigate. Needed for AMD skunk.
C: Excavator. This one is tricky. First off it requires Admin rights. Second it launches a server in a command window that needs to remain open. Your script is trying to open a window for each card but when i ran Excavator with the new NiceHash tool thats not how it behaved. All mining activity happened inside that server window. Also Excavator shuts down the Radeon tool and attempts to directly modify the bios of each card. So for folks like me that have already modded the bios this causes Excavator to fail and crash.
Excavator for me was faster then Claymore when I could get it to run. It tunes the cards and actually slowly gets better!
I would suggest making it optional in the batch file. -Excavator true / false
Awesome tool if you get it working. Crashes like crazy if your already bios modded.

Thanks...

**Comment by alucard20724** [comment]
prospector for skunk works for my 470/480/570/580 with the blockchain drivers and works with my Vega64s with 17.8.2 drivers.    i honestly wouldn't bother with Gatelessgate and Excavator, Claymore is faster on my systems as long as you dial in the intensity for claymore (i.e.   -dcri #).

**Comment by imrecsoka** [comment]
Never seen a better miner than Claymore yet.
Still trying to understand this EPOCH / DAG crap because mine always seems to jump from 139 to 140 to 145, i dont understand this.
I use RX470 and 16.11.1 drivers.
I should be getting about 24 Megahashes but for some reason i get 22 - 23 and then at times i get 25 - 26 , i dont understand how the hell it just changes.
I have no background or graphical tasks running , and i dont play street fighter while i mine.

**Comment by aaronsace** [comment]
It takes a week average so it won't effect MultiPoolMiner.

**Comment by imrecsoka** [comment]
What takes a week average ?  
a)Still trying to understand this EPOCH / DAG crap because mine always seems to jump from 139 to 140 to 145, i dont understand this- i do understand that the EPOCH is going up and mining speeds will slow down over time.... BUT my issue is at the very moment when the claymore miner starts it is great and constant, and then it doesnt somehting and it gets less hash rate , i dont get it.
b)There is a different between the start.bat and the startgb2.bat in that the claymore eth speed is different by 1 or 2 Megahashes, i dont get why, but it is true.
c)can i use any of your batch files to mine ? im asking in general....
d) i also wanted to know , what is the -wallet option in the batch file? Do i leave the one in there already or do i use my one? -donate i see still exists , that i leave at 15.

**Comment by aaronsace** [comment]
@Imaminer Ethash is odd; the speed varies depending on the size of the dag due to different coin difficulties. I wouldn't worry about your speed fluctuating a bit. Also, heat will cause the GPU to cap the speed when the temperature limit is reached. A wallet is needed for the other pools to work.
