### ISSUE TITLE
running the miner for the first time

### ISSUE THREAD

**Issue by imrecsoka** [aaronsace/MultiPoolMiner#319]
When i run the start.bat all the benchmarks run and then mining starts.
When the start2gb.bat runs it also benchmarks:
I noticed:----
start2gb.bat contains - - - -- - - - - - - - - - start.bat contains
-poolname miningpoolhubcoins  - - - - - - -poolname miningpoolhub
i also have : -algorithm cryptonight,decred,ethash2gb,equihash,pascal,sia,sib,skein -poolname miningpoolhubcoins -currency btc,usd -donate 25"
which is in the start2gb.bat    
When i check https://miningpoolhub.com/?page=account&action=balances
i dont see the stuff , only monero, i dont see ethash or whatever, please help me?

**Comment by imrecsoka** [comment]
My point being i would like to use the start2gb.bat because the ethereum seems to be 1-2 Megahashes quicker, it makes a difference for me me , even if it is 20 cents i really mind this, it is my effort worth.

**Comment by aaronsace** [comment]
If you don't want to mine Ethereum then just select Ethash2gb instead of Ethash. 

Regarding balances, that's pool related and not to do with MutiPoolMiner. The pool is working so my guess is that you just haven't waited long enough. Pools don't just pay you for hash like a pay-as-you-go tariff; miners pool their resources together in the hope to find a block first then for a reward to be confirmed and distributed amongst everyone involved.
