### ISSUE TITLE
stratum servers and mining is still online on zpool.ca

### ISSUE THREAD

**Issue by spider703** [aaronsace/MultiPoolMiner#357]
on the pool there was a hacking, the web page is disabled, the miner itself works if it is forced to run it, it does not work through MPM, how to fix it?

**Comment by UselessGuru** [comment]
MPM fails because it cannot retrieve pricing information from the server.

`$Zpool_Request = Invoke-WebRequest "http://www.zpool.ca/api/status" -UseBasicParsing | ConvertFrom-Json` fails.

Only cached requests would help, but then you would work with old data. I have implemented this in my code as described in

**Comment by aaronsace** [comment]
MiningPoolHub and NiceHash are still running fine and there is no interruption with MultiPoolMiner. Once Zpool front end is back up then it will resume using Zpool automatically.
