### ISSUE TITLE
Old miners does not close

### ISSUE THREAD

**Issue by jjziets** [aaronsace/MultiPoolMiner#377]
For some reason, I find that I have old miners still running. 
Windows 10. Nvidia 1070 systems. 
![image](https://user-images.githubusercontent.com/19214485/30524756-a3e6b0be-9bf9-11e7-9aca-d924f0ce8455.png)
![image](https://user-images.githubusercontent.com/19214485/30524761-b79d8740-9bf9-11e7-97a2-d31fbbc61e46.png)

**Comment by fonyo** [comment]
Most likely you overclock too much and your miner fails. When failed miner is detected a new istance will be opened, however, the old miner cannot always be closed due to duplicated port issues. This is kind of a bug and not but will be improved upon soon. Overclocking is definitely the root cause in most cases and seeing a rejected share above makes me have the same conclusion here as well.

**Comment by fonyo** [comment]
Do not close please until added to FAQ.

**Comment by fonyo** [comment]
You might also want to check your undervolt as too much of that can cause the same problem. Also, try klaust's ccminer, it can be faster in many cases and v8.13 which is now included in the latest MPM releases, has fixed the stratum timeout/connection issues. ;)

**Comment by jjziets** [comment]
:-) I  think it has to do with me adding cpu. I removed it and now i don't get more than one miner running.

**Comment by fonyo** [comment]
I don't see why mining with CPU would cause such issue. Which version of MPM are you running?

**Comment by aaronsace** [comment]
The CPU miner was most likely locking MultiPoolMiner up and is failing to get the process ID (note the failed miners in your screenshot). I've reduced the process priority in the latest code branch. 

Something needs to be changed to ensure it always obtains the process ID but I'm not sure what yet. During normal operation, I've never found this to ever be an issue on my machine...
