### ISSUE TITLE
Pool fee adjustments

### ISSUE THREAD

**Issue by mjmeans** [aaronsace/MultiPoolMiner#409]
There seems to be a very strong argument that zpool may have a hidden 20% fee due to the way it performs the auto-exchange and credits based on an 80% weighted average of the current btc bid price against a (somehow) lost prior value. Info is [here](https://bitcointalk.org/index.php?topic=1951402.60). While this is not a specific issue with MPM, a method to account for pool fees and aggregate exchange fees in MPM is needed. Especially if a pool has a much larger aggregate loss due to various fees at various levels compared to another pool.

**Comment by aaronsace** [comment]
I'm aware of the problem; crackfoo shut the previous forum down because I and others wouldn't stop talking about it. Nobody has anything concrete and the problem isn't getting fixed. Crackfoo has all the info but he has no idea how his own pool works. He pays other developers then he just hosts it and rakes in the money. 

I think it's a use it or don't situation.

**Comment by UselessGuru** [comment]
I implemented a solution based on a variable '$ProfitFactor' in all pool files, see attached file 
for an example.

[ZpoolCoins.ps1.txt](https://github.com/aaronsace/MultiPoolMiner/files/1358734/ZpoolCoins.ps1.txt)

**Comment by aaronsace** [comment]
What could be done is compare the 24 estimate and the 24 hour actual on the Zpool API over time by using Set-Stat. That's assuming the actual is correct. Then input that figure into $ProfitFactor on the file from @UselessGuru. If you want to try it.

**Comment by Pititul** [comment]
I'm kind of skeptical about Zpool fee. I'm gonna try your ZpoolCoins.ps1 this week.
