### ISSUE TITLE
Klaust 8.14beta-cuda 9 (neoscrypt) 

### ISSUE THREAD

**Issue by nemosminer** [aaronsace/MultiPoolMiner#448]
8.14beta-cuda 9 is released, im seeing speed improvements on my 1060 and 1070 (neoscrypt) test rigs sadly 1080ti seems to still be faster with tpruvot 2.2 cuda 8.  im not getting any connection issues so far : 

https://github.com/KlausT/ccminer/releases/download/8.14beta/ccminer-814beta-x64-cuda9.zip

Regards
Nemo

**Comment by UselessGuru** [comment]
If anyone want to use my miner file.
It is optimized for GTX 1080 ti (+333MHz Mem Clock)
Rename it to .ps1 and copy it to the 'miners' folder.
[CcminerKlaust814b.ps1.txt](https://github.com/aaronsace/MultiPoolMiner/files/1404662/CcminerKlaust814b.ps1.txt)

**Comment by AcharyaOne** [comment]
I've got a weird situation with neoscrypt miners, klaust or alexis, they keep exiting constantly while mining, but when I try to run it outside of multipoolminer they seem stable for a long period, I've tried to increase cpu-priority to 5 but it seems to make no difference. I thought it could be because of overclock but since they seem to run fine on stand alone I'm honestly not sure what it is.

**Comment by jjziets** [comment]
-I 17.24 seems to gives amazing results in 1070

**Comment by jjziets** [comment]
What driver are you on? I am using 385.69.
this is a 7 x MSI Armor 1070 OC rig.
 
![image](https://user-images.githubusercontent.com/19214485/31949075-b92da60c-b8d8-11e7-8fc4-b7f701d2b9b3.png)

**Comment by fonyo** [comment]
Neoscrypt is a weird one, I see it jump up to the top frequently but not for too long. By the time miner jumps on it, the profit train is (almost) gone and since pools are using pplns, it basically becomes a waste of time and power. I am getting higher and more consistent profits since I excluded from the algorithm list.

**Comment by FruitFace** [comment]
I'm running 389.98.  I'll DDU and try your version.

**Comment by jjziets** [comment]
I am doing the opposite for now. Mining Neoscrypt constantly. Will see if this gives better results. I am also starting to think that it is better to focus on more established coin rather than jumping all the time to lower hash rates once. The problem is that once the global hash rates drop then it looks to be very profitable. But then when we switch we all drive up the competition and therefore dilute the prohibitive.

This reminds me of pool hopping with PPS pools.   Good and Bad times.

**Comment by jjziets** [comment]
@FruitFace my Asus 1070 OC can't run -i 17 but my all my MSI armor 1070 OC can.

**Comment by FruitFace** [comment]
@jjziets Let me know what happens with you Neoscrypt only mining.  Interesting to know that some cards don't like higher intensities.  I guess it could be my OC\underclock too.

**Comment by jjziets** [comment]
I am running it for +24h and average actual income in my wallet has been just over $2 per 1070.

Whattomine showed that for the last 24h it should have been $2.1 I did have a bit of down time so will repeat it today. But so far it looks good.

**Comment by AcharyaOne** [comment]
@jjziets I also have asus 1070 oc, what intensity you use? It keeps exiting on default settings but outside of multipoolminer seems to run fine.

**Comment by Pititul** [comment]
@UselessGuru in your ps1... what is this miner Palgin-Nist5 is it Alexis78 1.1.1 Palginmod?

**Comment by fonyo** [comment]
So how's the continuous neoscrypt mining working out for everyone? Can you please post results?

**Comment by UselessGuru** [comment]
@Pititul 

> in your ps1... what is this miner Palgin-Nist5 is it Alexis78 1.1.1 Palginmod?

$Uri = "https://github.com/palginpav/ccminer/releases/download/1.1-nist5/palginmod_1.1_nist5_x86.zip"

**Comment by Pititul** [comment]
@fonyo I'm on AHashPool now and the interval is set for 15 mins. Mine switches around neoscrypt, x17, xevan, myr-gr... Most of the time it stays on neoscrypt (more that 1 hour at a time). It is a must-have algo for my batch. I also set NH as my backup with Equihash and Ethash. 3 x 1070 = 0.001 per day.

**Comment by fonyo** [comment]
That sounds good with the current prices!

**Comment by Pititul** [comment]
![screenshot_20171105-115321](https://user-images.githubusercontent.com/31348011/32412116-17841358-c220-11e7-8229-4e0a0131968d.png)

**Comment by Pititul** [comment]
Altough, unlike other algos, the frequency of accepted share is very low. Not sure if that's a bad or good thing.

**Comment by fonyo** [comment]
Is this MobileCash coin any good, and is it consistently better? If so, we could request MPH to add it to extend the lyra2rev2 portfolio.

Getting fewer accepted shares is not always a bad thing. Pools tend to decrease the load by increasing the work difficulty so you don't spam them and they don't spam you, and unless you get too high diff jobs, it should be fine. It could also mean the pool's network share is low (small pool) and does not find many blocks.

**Comment by Pititul** [comment]
MobileCash is at the bottom in profit making but it only takes 3 minutes (zpool) to find a block. Anyway, I keep Lyra2v2 for XVG, MONA and VTC.
