### ISSUE TITLE
Excavator dual miner

### ISSUE THREAD

**Issue by Steality** [aaronsace/MultiPoolMiner#454]
Hi, due to issues of claymore dual miner crash when algo switch, is there any example for excavator dual miner setup? I cant seems to make it work through miners folder.

**Comment by Steality** [comment]
I am using 1070 x 3  and claymore crash shows "cu_k1 failed 4" only if it switch back from another algo. I am thinking to use excavator dual mining as substitute.

**Comment by aaronsace** [comment]
I've not done it yet but you just add threads of different algorithms instead of the same algorithm. Will update as soon as. 

BTW, changing wrap from false to true may bypass the claymore problem. 

He still hasn't fixed the restart problem; claymore should not attempt to restart: 
https://bitcointalk.org/index.php?topic=1433925.msg21475400#msg21475400

**Comment by spider703** [comment]
new version https://github.com/nicehash/excavator/releases/
