### ISSUE TITLE
X17 Phi Xevan Crashing

### ISSUE THREAD

**Issue by Pititul** [aaronsace/MultiPoolMiner#507]
Hey guys. These 3 algo X17 (Alexis), Phi (Tpruvot 2.2.2) and Xevan (Krnlx) keep crashing on me in the A Hash Pool. And since I have 20 interval, it takes 20 mins to reload. Other alo using the same ccminers work fine. Does anybody mine on this pool? Do you know if this causes by the pool or the ccminer (or my oc)? By the way, when these algo work, they pay very well.

**Comment by imrecsoka** [comment]
how do they run, do they run automatically?
do you need to specify them in the start.bat file?
like xevan,phi, or what?
I just leave defaults, i thought that was the purpose of this mining suite , to leave it all as is, and then donate also.

**Comment by fonyo** [comment]
Some basic configuration is required even with one-click-miners. And this is not a one-click-miner, however it is not that difficult to set up and customise. There is a README to explain. @Pititul had customised his MPM instance even further probably to include other pools and miners. This, however, require some coding skills and are not recommended for users lacking these. 3 cards will certainly  not make you rich, no matter how hard you try. Your current income should be hovering around 5-6 but 8 USD at best and only occasionally. The times when a single RX480 could earn 7-8 bucks a day are long gone. 2 USD per 1070 per day is a realistic income. You should not expect more.

**Comment by aaronsace** [comment]
The machine that I test it on has a AMD RX 480 and NVIDIA GTX 1080 Ti. The current release works with the defaults. If you want to mine Xevan then specify it in the bat file.

**Comment by aaronsace** [comment]
@Pititul I have not tested those algorithms but if they are crashing then the problem is either your cards or the miners. My guess is that it is the cards if all three miners are crashing. Check drivers and OC then report to the developers if they are still not working. 

You need to set the interval to 1 or 2 minutes for MultiPoolMiner to work effectively.

**Comment by Pititul** [comment]
I fixed the phi by chaging it to Tpruvot x86... For xevan, I added 21 intensity as stated by the developer. X17 still crashing after a while.

@aaronsace I'm give it a try with 120 sec. See if the profit is the same. Thank you.
@fonyo I know 3 cards won't make me rich. I get that. I'm only trying to keep it running with out crashing while I sleep. BTW, my income is around 0.0007-8. Sadly, I dont think it will go any further.

**Comment by alucard20724** [comment]
those algorithms work fine for me.   I'm running 388.31 drivers.   if you are overclocking, you might want to reduce your overclocks.

**Comment by imrecsoka** [comment]
Hi Aaron, i need to understand how do i know what i can specify in the start.bat file 
I would like to educate myself.
I would guess i can say , xevan, or something like ,solaris, urals, not sure?
Is there a list i can see?

**Comment by aaronsace** [comment]
@fonyo has done a comprehensive read me. 

Advanced users can add even more.

**Comment by fonyo** [comment]
IDK but I find it miracleous how things I say (and I tend to be clear & concise) can just go over people's head.

**Comment by aaronsace** [comment]
@fonyo I can say for certain, you're not the problem; you are far better than most people.

**Comment by imrecsoka** [comment]
Thanks Fonyo and Aaron, i will read it, and see how  fair.

**Comment by fonyo** [comment]
Sometimes you just better off sticking to what you already know. If you can achieve 6 usd a day with your 3x1070 rig especially when it is not a dedicated mining machine, I would say, you should be very (!) happy with it. Please don't take any offense, just trying to be honest here, but with your knowledge I wouldn't push it any further. You will cause yourself headaches and downtime and you will end up hating the whole crypto biz. I saw happen the same to very knowledgeable IT professionals/programmers. Crypto is not just about IT, it is also around economics and complex calculations equally. Lately, it is more around economics and maths than software and IT.

I am not saying you should stop learning but just don't try to push it. Just an advice for you, matey, before you burn out.

**Comment by imrecsoka** [comment]
Hi, i feel like i am missing out and so ai am trying to explore other coins or alternatives.
I use NHM and MPM but im really not sure if i have the right/most correct version for my sake.
I have noticed that some older NHM suites actually pull more cents than newer ones.
I say cents and not dollars simply because i am talking about 3 RX470 cards.
Im responding regardless if you are replying to me or not - i see you mentioned 3X 1070 cards... so maybe you are responding to somebody else above.
Obviously me playing around with other coins or exploring other nooks and crannies i am losing out on leaving MPM or NHM to just do its thing.
So that was my feed back on NHM that some versions/underlying miners perform better than others.
Really unsure of Multipool miner now, I dont see usage of xmrig which for me seems to be better performing than xmr-stak-cpu but yet i dont see MPM making use of this, which i dont understand since the benchmark would prove this.
I will be trying MultiPoolMinerV2.7.0.2.zip and see how it goes.
I will probably just strip down the algos, and ask for benches on 3 or 4 instead of the whole lot for now just to see how it goes.
Thanks again for the feedback.

**Comment by Pititul** [comment]
@imrecsoka the third comment was a reply to you and me both.

You have to modify your start.bat. The one given to you was just a starter, you have to find the right algo and pool yourself.

**Comment by Pititul** [comment]
@imrecsoka Check here http://zpool.ca/bench?algo=all&chip=0 for algo and gpu.

**Comment by fonyo** [comment]
@imrecsoka I thought you had 3x1070 cards, my bad. Roughly 2 USD income also applies to the RX cards.
