### ISSUE TITLE
how to reboot computer after lost an nvidia gpu ?

### ISSUE THREAD

**Issue by SHOBU007** [aaronsace/MultiPoolMiner#622]
Hello,

I got a question : 
Is there a way to reboot the whole system when a gpu is lost ?
I got 3 gpu's on my system and one is lost from time to time.

Have a nice day!

**Comment by Renegade5399** [comment]
Is the GPU in question on a riser?

**Comment by SHOBU007** [comment]
Hello @Renegade5399 ,

The GPU is on an extender cable pcie x16 to pcie x16.

**Comment by cmbconcretefire** [comment]
Hello, I was having a similar issue with a different miner. I can tell you the answer lies in a program called 'nvidiainspector' . I can't tell you details because I don't know. All I know is that program can try to jump start the lost gpu, and works well. You'll have to dig deeper on your own unless someone else answers you.

**Comment by SHOBU007** [comment]
Hello @cmbconcretefire,

Thanks for the reply ! I will try to play a little with that program thank you ! 
I will edit the post accordingly.

**Comment by SHOBU007** [comment]
I managed to manually jump start it from device manager instead of restarting the whole system. Thank you !
