### ISSUE TITLE
Hangs almost every day

### ISSUE THREAD

**Issue by mjmeans** [aaronsace/MultiPoolMiner#625]
Was using NH for a month. Occasionally hung, maybe once a week. Now using MPM. Checking it twice a day. Hangs once or twice a day at random times. In last 4 days, typical day has only 10 hours of useful mining. The rest of the time it's hung. Hard hang. Only way to recover is to reboot PC with reset switch, keyboard CTL+ALT+DEL reboot doesn't work. Now using 2.7.0.2. Seems much less stable than the last time I tried MPM about 3 months ago.

**Comment by UselessGuru** [comment]
Most likely it is not MPM that causes the hang. 
I assume that you either have a general stability issue with your system, or that one of the miners is causing the lockup.
What does the log file say? What is the last miner running when it got locked up?

**Comment by Renegade5399** [comment]
Issue is most likely caused by unstable GPU. If using PCIe risers, one may be possibly bad. Otherwise possible unstable overclock.

Lyra2RE2 is great for testing stability IMO. I mined MONA with ccminer on each of my GPU's separately for 3 days and adjusted settings until they had no crashes or errors. MPM works perfectly with no lockups on 2 different mining boxes after doing this.

**Comment by robl45** [comment]
I don't know if its related, but I've noticed something similar.  In my case, the miner will keep going, but the CMD window will stop updating so it will just sit with the same miner forever if I don't close the cmd and restart it.

**Comment by mjmeans** [comment]
As I said in the original post. NH miner runs fine. There must be something specific about MPM that is causing the hangs. But I suppose I can take Lyra2RE2 out of the algos to see if that is part of the problem.

**Comment by aaronsace** [comment]
MultiPoolMiner cannot cause any system hangs. It is exactly the same as running each individual miner yourself. The command lines are shown on the screen so if they so, if they do not match the settings that you normally use, change them in the miners folder. Each miner file is 100% configurable and can also be removed.

**Comment by FruitFace** [comment]
In my case I was getting blue screens, mostly IRQ not less or equal BSODs.  It turned out to be Excavator.  I tried the most recent, and the version prior.

My machine would run for between 4-12 hours, and then would have mysteriously rebooted.  Sometimes, I was watching a movie, and it would just BSOD on me.  Since I removed excavator, no more BSODs.  I've been mining without a hiccup for 30 hours now.

**Comment by sipper100** [comment]
Same thing for me. Was using NH and my rig ran for weeks without needing to reboot, With MPM it's crashing every 2-4 hours. Been looking through the logs but it's inconclusive, seems to be many different miners. My rig rarely runs Excavator but I'll try removing that.

**Comment by UselessGuru** [comment]
This is the same as

[https://github.com/aaronsace/MultiPoolMiner/issues/639](https://github.com/aaronsace/MultiPoolMiner/issues/639)
