### ISSUE TITLE
MPM compatibility with zpool?

### ISSUE THREAD

**Issue by lmlim** [aaronsace/MultiPoolMiner#642]
Hi Aaronsace,

I understand that MPM is fully compatible with MPH's multi algo switching, ie: MPM will switch to different miner program if current task/miner has found a block. thus, PPLNS payment will be maxed.

i recently add zpool in "-poolname miningpoolhub,zpool" option.
i am curious if MPM also apply the same rule for switching as above? because i saw MPM switch more often in zpool than in MPH.

**Comment by aaronsace** [comment]
Zpool has no switching loss and is the best pool for NVidia cards where Ethereum is not profitable. 

I'm going to reduce the switch for MiningPoolHub but he is making it very hard with the cached API.

**Comment by lmlim** [comment]
thanks for pointing out zpool for nvidia cards. it has amazing rates at times, indeed.

**Comment by drewcoins** [comment]
i've read some posts about zpool taking a huge fee like around 20% .... anyone experiencing that?

**Comment by aaronsace** [comment]
I was part of the derailment of the first Zpool thread on Bitcointalk. Honestly the guy that runs it just isn't an engineer and pays others to make amendments. There is no 20% loss, just overestimated gains. Just look at the sheer number of algorithms and coins; it's amazing that it manages to work but it does work and it actually works well.

**Comment by drewcoins** [comment]
i see... so most of you guys are seeing better profits with zpool than MPH ? I've been on both the last couple weeks, but last couple days I switched to only MPH when I saw those threads I mentioned, but I trust you know what you're talking about.... So, currently zpool is best profits for Nvidia cards you're saying?

**Comment by Jaerin** [comment]
Zpool does work well, but the payouts do seem to be affected by something.  I'm not so sure its just a display problem because if you look at ahashpool.com it runs the same software with the AverageIncrement 20% bug fixed and the payout is always significantly higher.  I did some pretty extensive tests in the thread on bitcointalk and it certainly looked to me like every coin that was actually exchanged was paying out significantly less than the lowest market value for the day that it was supposed to be exchanging.  Its a simply fix and yet I still get called a troll for pointing it out.  Wish the Equihash code for Yiimp wasn't private then I wouldn't have to care about Zpool at all.  When you finally get ahashpool implemented in the release of MPM you'll like see that is what dominates your mining.

**Comment by drewcoins** [comment]
interestingly... MPminer shows that on one of my machines, it should be making between $16-25 usd.... but i'm averaging about $5-8 . That scales for both of my machines roughly. I'm still testing, but that seems to be for both zpool and MPH, with MPH looking the better of the two so far.

**Comment by Jaerin** [comment]
The problem with MPH that I've found is that MPM can switch algorithms quite a few times normally because it checks every 60 seconds.  MPH is a PPLNS pool so it is actually more beneficial to mine one algorithm until a block is found and then switch.  I don't think there is any easy way to code that into MPM so you end up getting penalized a bit due to some lost shares.

**Comment by lmlim** [comment]
@Jaerin and @drewcoins thanks for sharing some insights.

@aaronsace i saw my friend rigs (using awesome miner), his AMDs can mine NIST5 and others in zpool, can you also include as many miners for AMD as possible for mining in zpool?

**Comment by drewcoins** [comment]
Forgive my ignorance please.... but couldn't the miner be programmed to only switch after a block has been found? so that there is no "loss" from MPH ?

**Comment by aaronsace** [comment]
@drewcoins That's exactly what I want to do.
