### ISSUE TITLE
How to bind MPM to just one gpu? 

### ISSUE THREAD

**Issue by SomeAnonGuy** [aaronsace/MultiPoolMiner#73]
So I've been looking through the scripts and can't seem to find any comments or references for limiting MPM to running on just one GPU, while I allow the others to do whatever else. 

Is there some way to configure the scrips for this? In the same vein, is it possible to omit certain GPU's from certain mining programs?  

-Edit-

Also wondering if there's a way to disable algorithms altogether, and manually tweak intensities or whatever other parameters.

**Comment by aaronsace** [comment]
I don't think it's that simple otherwise I would add an option. I may be wrong but the order of the GPUs on each miner is not necessarily the same. You can edit all the miner command lines in the folder called 'miners' using notepad. I would like to do what you are trying to do natively at some point. 

You can chose your algorithms in the latest version; check 'start.bat' example. 
Intensities are individual miner specific options and are not generic so you will have to edit in notepad, as above.

**Comment by SomeAnonGuy** [comment]
Appreciate the quick response! I just dug through the miner's folder and did some changing around, and so far it's good. I just have to set aside the time to manually edit them and try out some manual tweaking for each card. I have a 290 and two 7850s, and the 290 can seemingly run any algo. The 7850s however, I can't seem to get them to run Ethash, Equihash or Cryptonite at anything stable, or at appreciable hashrates although I've seen other's getting decent results with these cards.

I think I may just use the 290 as a dedicated coin trickler (Hooray free power) and keep the 7850s on nicehash.

**Comment by aaronsace** [comment]
Yeah, 290s and 480s work well. I'll look at improving this in future. Glad you got it working. :D
