### ISSUE TITLE
Why all Pools?

### ISSUE THREAD

**Issue by Menelaous** [aaronsace/MultiPoolMiner#772]
HI,

my Setup is:

cd %~dp0

setx GPU_FORCE_64BIT_PTR 1
setx GPU_MAX_HEAP_SIZE 100
setx GPU_USE_SYNC_OBJECTS 1
setx GPU_MAX_ALLOC_PERCENT 100
setx GPU_SINGLE_ALLOC_PERCENT 100

set "command=& .\multipoolminer.ps1 -wallet XXXXXXXX -username XXXXXXX-workername XXXXXXX-region europe -currency btc,usd,eur -type nvidia,cpu -poolname miningpoolhub,miningpoolhubcoins -algorithm cryptonight,ethash,ethash2gb,equihash,groestl,lyra2re2,lyra2z,neoscrypt,siaclaymore -donate 0 -watchdog"

pwsh -noexit -executionpolicy bypass -windowstyle maximized -command "%command%"
powershell -version 5.0 -noexit -executionpolicy bypass -windowstyle maximized -command "%command%"
msiexec -i https://github.com/PowerShell/PowerShell/releases/download/v6.0.0-rc.2/PowerShell-6.0.0-rc.2-win-x64.msi -qb!
pwsh -noexit -executionpolicy bypass -windowstyle maximized -command "%command%"

pause

it should only take miningpoolhub as pool, but it mine on zpool, ahashpool, hashrefinery too.

<img width="1164" alt="pools" src="https://user-images.githubusercontent.com/34719946/34221252-a97fd570-e5b7-11e7-8ea8-4863fa094d49.PNG">

i don't know why it mine on the other pools.

thx

**Comment by jayntguru** [comment]
Delete them out of the pools folder and it won't do that.

**Comment by Menelaous** [comment]
ok, thx

**Comment by zoglun** [comment]
Got same problem here. It seems the -poolname setting totally failed.

**Comment by jayntguru** [comment]
If you have an algo in the list that isn't in one of the pools you have selected, it will use the pools in the pools folder to try and find a way to mine that algo. So you need to either make your algo list match the pools you are mining against (which is the real fix) or delete the pool that keeps showing up.

I don't think this is in the FAQ. Probably should be.

You can use this creatively. It's how I mine eth only at MPH. Leave it in the list (the algo), pick other pools and when eth is profitable but only for that it'll hit MPH. Since it finds the other algos I selected at the pools I selected, they don't get hit. It's great for that. Pools you select take priority if the algo exists there. Hope this makes sense.

**Comment by paulpoco** [comment]
Remove your wallet address

**Comment by aaronsace** [comment]
@Menelaous All your miners are losing hashrate. Either fix the issue or turn off watchdog if you're not that bothered.
