### ISSUE TITLE
Autoexchange - general question/s

### ISSUE THREAD

**Issue by imrecsoka** [aaronsace/MultiPoolMiner#91]
Hello, i have waited a bit and not sure if weekends are different, but i noticed that the Credited -> Credit for Auto Exchange -> On Exchange process is taking sometime.
Is this a normal thing and i should remain patient?

**Comment by somidax** [comment]
Hello,

Just remain patient for it takes a bit longer but their auto exchange is
cool.

I have used it almost all the time and mostly when your coins have not been
confirm for I guess u will have known "skelling issues with coins due to
high demands"

Just wait ok or just cash out manually if u can't have patient.

Regards!

**Comment by imrecsoka** [comment]
I have been waiting for my maxcoin to go to auto exchange and its been 1 week now.
I have clicked the right arrow also on the wallet screen , and still waiting.
I am not sure why.
I will still just wait.
